### ISSUE TITLE
最hign部分怎么判断的

### ISSUE THREAD

**Issue by newpost** [xinshangshangxin/music#1]

**Comment by xinshangshangxin** [comment]
代码部分在 [audio-peak.ts, L9-L30](https://github.com/xinshangshangxin/music/blob/develop/frontend/src/app/rx-audio/audio-peak.ts#L9-L30)

简单描述:
1: 获取 arrayBuffer
2: 获取 channelData
3: 将 channelData 等分成X份(假设X份 = 歌曲总时长(秒) / 0.1(秒), 这样就是每0.1秒为1份), 每份假设为D
4: 每份D中, 有很多 channelData[index] 的数据, 找个算法获取一个可以标识 每份D的 "平均值"
5: 等分成X份的, 在T 秒内  找一个算法 获取 "最大值", 这个最大值就是 最high部分的开始时间

- *其实4/5可以合并成一步, 就不用计算2次了*
- *fetch的时候可能有跨域问题, 要后端中转下*

额, 语言描述不是很清楚, 可以看代码
