### ISSUE TITLE
iphone 浏览器打开空白！！！

### ISSUE THREAD

**Issue by lrm929** [xinshangshangxin/music#2]

**Comment by xinshangshangxin** [comment]
`Safari` 有很多兼容问题

当前页面可以显示, 但是听歌还存在问题, 后面有时间再修复


修复代码:
https://github.com/xinshangshangxin/music/commit/a0eeb35fb25b331c8f0a91828c5db29976aa0ad7
https://github.com/xinshangshangxin/music/commit/49845e999275f253e92a5b83ad50bec61ad5ac37
